name: ServerChangeGui
main: ga.dingemans.bigibas123.ServerChangeGui.ServerChangeGui
version: 1.0
commands: 
  SCG:
    permission: ServerChangeGui.use
    usage: /SCG
    description: Main command of ServerChangeGui
    permission-message: You don't have permission ServerChangeGui.use on this server!
