name: ServerChangeGui
main: ServerChangeGui
version: 1.2
commands: 
  SCG:
    permission: SCG.use
    usage: /SCG
    description: Main command of ServerChangeGui
    permission-message: You don't have permission &bServerChangeGui.use on this server!
